version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - ENV=prod
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/caremo
      - REDIS_URL=redis://redis:6379/0

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caremo

  redis:
    image: redis:7
